In [15]:
import torch
import torch.nn as nn

class CustomNet(nn.Module):
    def __init__(self):
        super(CustomNet, self).__init__()
        self.fc1 = nn.Linear(4, 6)
        self.fc2 = nn.Linear(6, 8)
        self.fc3 = nn.Linear(8, 4)
        self.fc4 = nn.Linear(4, 4)
        self.fc5 = nn.Linear(4, 2)

        self.leaky_relu = nn.LeakyReLU()   
        self.tanh = nn.Tanh()              
        self.sigmoid = nn.Sigmoid()        
        self.elu = nn.ELU()               
        self.softmax = nn.Softmax(dim=1)     

    def forward(self, x):
        x = self.leaky_relu(self.fc1(x))    
        x = self.tanh(self.fc2(x))          
        x = self.sigmoid(self.fc3(x))      
        x = self.elu(self.fc4(x))           
        x = self.softmax(self.fc5(x))      
        return x

if __name__ == "__main__":
    net = CustomNet()
    
    print("Neural Network Summary:")
    print(net)
    
    random_input = torch.randn(1, 4)
    
    output = net(random_input)
    
    print("\nRandom Input:")
    print(random_input)
    print("\nNetwork Output:")
    print(output)


Neural Network Summary:
CustomNet(
  (fc1): Linear(in_features=4, out_features=6, bias=True)
  (fc2): Linear(in_features=6, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=4, bias=True)
  (fc4): Linear(in_features=4, out_features=4, bias=True)
  (fc5): Linear(in_features=4, out_features=2, bias=True)
  (leaky_relu): LeakyReLU(negative_slope=0.01)
  (tanh): Tanh()
  (sigmoid): Sigmoid()
  (elu): ELU(alpha=1.0)
  (softmax): Softmax(dim=1)
)

Random Input:
tensor([[-1.5067, -0.4990,  0.5684,  0.7271]])

Network Output:
tensor([[0.3818, 0.6182]], grad_fn=<SoftmaxBackward0>)


In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class LeNet5(nn.Module):
    def __init__(self):
        super(LeNet5, self).__init__()
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=6, kernel_size=5)  
        self.conv2 = nn.Conv2d(in_channels=6, out_channels=16, kernel_size=5) 
        
        self.fc1 = nn.Linear(16 * 24 * 24, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = torch.tanh(self.conv1(x))
        x = torch.tanh(self.conv2(x))
        x = x.view(x.size(0), -1)
        x = torch.tanh(self.fc1(x))
        x = torch.tanh(self.fc2(x))
        x = self.fc3(x)
        return x

if __name__ == "__main__":
    net = LeNet5()
    print("Modified LeNet-5 CNN Summary:")
    print(net)
    
    random_input = torch.randn(1, 1, 32, 32)
    output = net(random_input)
    
    print("\nRandom Input:")
    print(random_input)
    print("\nNetwork Output:")
    print(output)


Modified LeNet-5 CNN Summary:
LeNet5(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=9216, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)

Random Input:
tensor([[[[ 0.9241, -1.6862,  0.9748,  ...,  0.7160, -0.0449,  1.3225],
          [ 1.1468,  0.9975, -0.5180,  ..., -1.1019,  1.2592, -0.3111],
          [ 0.3921,  1.1639,  2.4657,  ..., -0.1090, -0.0601,  1.3273],
          ...,
          [-0.6427,  0.1143,  0.3214,  ..., -1.0988, -0.3013, -0.0213],
          [ 0.3572, -0.7928,  0.8581,  ...,  0.4582, -0.0555, -0.0577],
          [ 0.5083,  0.2131, -1.2405,  ...,  1.1713, -0.4998, -0.7917]]]])

Network Output:
tensor([[-0.0313, -0.0633,  0.0133,  0.1623,  0.0084, -0.0127, -0.1603, -0.0980,
         -0.0042,  0.1199]], grad_fn=<AddmmBackward0>)
